### ISSUE TITLE
error displaying account

### ISSUE THREAD

**Issue by omer411** [jensb89/anchor-earnings#3]
error with accounts that use Kujira or whitewhale on the Terra Ecosystem.

**Comment by jensb89** [comment]
So it does not show the yield at all or is the yield wrong? 

I will have a look for a wallet with whitewhale and test it as soon I can find some time. 

Thx for opening the issue :)

**Comment by omer411** [comment]
Doesn't show anything at all

**Comment by omer411** [comment]
gives error  

Something went wrong with parsing the data. Please open a ticket: https://github.com/jensb89/anchor-earnings/issues

and chart and numbers are blank

![image](https://user-images.githubusercontent.com/97014987/155182204-1b1fe9fe-4511-47c3-b2cb-2aaad3c3b8dc.png)

**Comment by omer411** [comment]
i used https://finder.extraterrestrial.money/  to find some other address that have same issues mine does (issue seems to occur if you ever entered KuJI or Whitewhale or loop site)

https://anchor-earnings.herokuapp.com/address/terra1axdm6a6m7r07q70c5wtvqwtu6m92f566eps04x
https://anchor-earnings.herokuapp.com/address/terra1nq8rqhlreyjksupwmlj94efjfx8ped03qpgu9e
https://anchor-earnings.herokuapp.com/address/terra1jzkjvkgdjp9jpm62synd6uzzm92p62ath2fzd3
https://anchor-earnings.herokuapp.com/address/terra1d4gxv9d5jg3lp860qzykquhky46helrqu2yr9e

**Comment by jensb89** [comment]
That's very helpful, thanks. I will have a look

**Comment by jensb89** [comment]
Hm okay, I had a short look. The problem doesn't seem to be the White Whale or Kujira, at least the addresses you posted work fine locally.
The problem in these cases is that there are a lot of transactions and the script has to query the terra Api very often. The address with 9e at the end for example has around 30 pages of each 100 transactions.

The script simply runs into a "Too many requests error", I guess the waiting time between each API call of 10ms is too short for so many requests. After around 10 pages or so the terra Api denied the call. 

For testing purposes, I increased this time to 500ms and then it ran through without problems:

```
terra1nq8rqhlreyjksupwmlj94efjfx8ped03qpgu9e
Yield
Total Yield:
2703.87 UST (2385.23EUR)
Holdings:
50572.91 UST (44613.15EUR)
42190.59 aUST
```

Simply increasing the time for the website however might not be a good idea:
1. It slows down the calls and loading time for people with not so many transactions
2. The Heroku server runs into a timeout after maximum 30s (probably even earlier) 

This seems to be a serious issue. When I started the project it was just meant for me to check my yield, quickly coded on a weekend. Such cases with many transactions may require a rethinking. Something like an async call running in the background and a progress bar showing the update process to the user would be needed I guess.  The code itself could use some refactoring too :) 

I will think about how these changes could be done without spending money for an extra layer service. At least this will not be a quick fix.

For a quick fix we could think about increasing the sleep time slightly (not so drastically to 500ms), maybe there is a better value, I couldn't find the official request time limit yet. This might help in the short run :)

**Comment by omer411** [comment]
what about this one 
https://anchor-earnings.herokuapp.com/address/terra1kfx8keps62qh7k7lj9cht4gykymypg87c2lh53

**Comment by omer411** [comment]
and how do i increase time on my end... havent run locally before only on site

**Comment by jensb89** [comment]
Ah yes, that one actually has an error that is related with Kuji. Will look into that one

In the "anchorProtocol.py" there is a sleep time: "sleep(0.01)". Increase this to 0.5 for example.
To run locally install the dependencies in a virtual environment and then call "export FLASK_DEBUG=1 && flask run"

**Comment by jensb89** [comment]
Seems for Kuji the aUST contract is called with an action "increase_allowance", where typically "send" (redeem aUST) or "transfer" (to transfer aUST) were used in other transactions.

For now I don't have the time to look deeper into it, but I just pushed a commit to ignore all unknown transactions that differ from "send" or "transfer". These will now show a warning, but at least you should be able to see your "other" holdings and the calculated yield.

**Comment by omer411** [comment]
thanks for all the hard work.  looking forward to update

**Comment by omer411** [comment]
this site might help also
https://beta.trackterra.org/

**Comment by omer411** [comment]
any updates on this?  graph not updating

**Comment by jensb89** [comment]
Well yes, kind of.
I did a little refactoring yesterday to speed up the performance. 
Also a few minutes ago I pushed a fix to wait longer when doing the requests so we don't run into a "too many requests" error. Still seems to be too low for wallets with a lot of txs and for these cases a database + a loading page would be more ideal. But that's not done in a day and I really don't have much time to do this right now or in the next couple of weeks.

Regarding the Kuji and WhiteWhale: The fix I posted 2 weeks ago should at least ignore them and show a graph. I pushed a fix just now to also search the additional logs for incoming/outgoing aUST transfers, that might show the ingoing/outgoing aUST as well. You can try it by calling the website with a "/full" at the end (e.g. address/terra1kfx8keps62qh7k7lj9cht4gykymypg87c2lh53/full)

Regarding WhiteWhale: Do they really have aUST transfers? I couldn't find anything about it. If you deposit into their arbitrage pool, you will get vUST and not aUST. In the end they also put the money in anchor, but they have their own token for it.

So when you say "graph is not updating", do you see no graph at all? It should at least show the regular anchor transfers (and hopefully now also the ones from kuji)

**Comment by omer411** [comment]
1. yes graph now works and does update interest earns
2. whitewhale you first deposit UST then they issues their own vUST token but does somehow gains the aUST interest rate

Again thanks for the commitment to updating this project.  wish anchor created something like this would be easy for them to do.

**Comment by jensb89** [comment]
Sry, forgot to answer., but I'm glad it worked and thanks for the feedback :) 

Regarding the vUST: You are right, they also use Anchor for the high gains, but technically it's a new token and at least the contract is not depositing to anchor in the same transaction as far as I can see. 

Still, I agree with you, it would be nice to see these gains as well, maybe even as a 2nd line in the graph. However, for this, I first need the historical vUST/UST rate through a different API and also get the amount of vUST for a specific wallet. I will create a new issue for that as a future to-do so I don't forget it and will see what I can do.
