### ISSUE TITLE
UstRate last updated 2 days ago

### ISSUE THREAD

**Issue by misterpip** [jensb89/anchor-earnings#5]
Hello,
the aUst to UST Rate was last update on 8 of May. From my understanding you are pulling the rates from here:
https://api.flipsidecrypto.com/api/v2/queries/1de96d09-4d77-4ad7-b0c8-e907e86fdcb7/data/latest

You have any insight into why it was not updated for the last 2 days?

thank you

**Comment by jensb89** [comment]
Thanks for opening the issue. In flipsidecrypto it was marked as "uptodate" even though it was not. I retriggered the query in flipside crypto and now the newest data is there. Unfortunately there is no other API source for historical rates :( 

Should work again now, but could still take another day to show up on the page, as the result is cached for some time to improve loading speed of the web app.
